#!/bin/bash

DISTBOX_IMAGE=registry.fedoraproject.org/fedora-toolbox:latest

DISTBOX_FILES=$HOME/distbox-files
DISTBOX_PODMAN=$DISTBOX_FILES/podman-files
DISTBOX_HOME=$DISTBOX_FILES/HOME

dbus_setup() {
    HOME=$DISTBOX_PODMAN podman exec my-distbox rm -f /run/dbus/pid
    HOME=$DISTBOX_PODMAN podman exec my-distbox dbus-daemon --system
    HOME=$DISTBOX_PODMAN podman exec --user=$USER my-distbox dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus 2> /dev/null &
}

if [ "$1" = "install" ]; then
    read -r -p "Do you want to install/replace your distbox? [y/N] " response
    if ! [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        exit
    fi

    echo y | distbox uninstall

    mkdir -p $DISTBOX_PODMAN/.config/containers $DISTBOX_HOME

    echo '[storage]
driver = "overlay"
runroot = "$HOME/.config/containers/storage"' > $DISTBOX_PODMAN/.config/containers/storage.conf

    HOME=$DISTBOX_PODMAN podman create \
        --hostname $HOSTNAME \
        --name my-distbox \
        --privileged \
        --security-opt label=disable \
        --security-opt apparmor=unconfined \
        --pids-limit=-1 \
        --user root:root \
        --shm-size $(df -h /dev/shm | awk '{ print $2 }' | sed -n 2p) \
        --network host \
        --label manager=distrobox \
        --label distrobox.unshare_groups=1 \
        --env SHELL=bash \
        --env HOME=/home/$USER \
        --env container=podman \
        --env CONTAINER_ID=my-distbox \
        --volume $HOME/.distbox-helpers/distrobox-init:/usr/bin/entrypoint:ro \
        --volume $DISTBOX_HOME:/home/$USER \
        --volume $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:ro \
        --volume $XDG_RUNTIME_DIR/pipewire-0:$XDG_RUNTIME_DIR/pipewire-0:ro \
        --annotation run.oci.keep_original_groups=1 \
        --ulimit host \
        --userns keep-id \
        --entrypoint /usr/bin/entrypoint $DISTBOX_IMAGE \
            --verbose \
            --name $USER \
            --user $(id -u) \
            --group $(id -g) \
            --home /home/$USER \
            --init 0 \
            --nvidia 0 \
            --pre-init-hooks '' \
            --additional-packages 'google-noto-color-emoji-fonts google-noto-sans-mono-fonts google-noto-sans-symbols2-fonts dbus-daemon libglvnd-gles gsettings-desktop-schemas dconf' -- '' || exit
    HOME=$DISTBOX_PODMAN podman untag $DISTBOX_IMAGE

    HOME=$DISTBOX_PODMAN $HOME/.distbox-helpers/distrobox-enter my-distbox --no-workdir -- ''
    HOME=$DISTBOX_PODMAN podman exec my-distbox chown $USER: $XDG_RUNTIME_DIR

    HOME=$DISTBOX_PODMAN podman exec my-distbox mkdir /run/dbus
    dbus_setup
    HOME=$DISTBOX_PODMAN podman exec my-distbox rm -f /etc/machine-id
    HOME=$DISTBOX_PODMAN podman exec my-distbox dbus-uuidgen --ensure=/etc/machine-id

    HOME=$DISTBOX_PODMAN podman exec --user=$USER my-distbox cp /etc/skel/.bashrc $HOME

    distbox run gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
    HOME=$DISTBOX_PODMAN podman exec my-distbox pkill dconf-service
    distbox run 'echo "exclude=*.i686" | sudo tee -a /etc/dnf/dnf.conf' > /dev/null
elif [ "$1" = "run" ]; then
    DISTBOX_OFFLINE=$(HOME=$DISTBOX_PODMAN podman exec my-distbox echo 2>&1)
    HOME=$DISTBOX_PODMAN podman start my-distbox > /dev/null
    if [ "$DISTBOX_OFFLINE" == "Error: can only create exec sessions on running containers: container state improper" ]; then
        dbus_setup
    fi

    HOME=$DISTBOX_PODMAN podman exec \
        --interactive \
        --detach-keys= \
        --user=root \
        --tty \
        --workdir=/home/$USER \
        --env HISTCONTROL=ignoredups \
        --env HISTSIZE=1000 \
        --env XDG_SESSION_TYPE=$XDG_SESSION_TYPE \
        --env LANG=$LANG \
        --env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
        --env TZ=$(timedatectl show --va -p Timezone) \
        --env DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus \
        --env WAYLAND_DISPLAY=$WAYLAND_DISPLAY \
    my-distbox \
        su $USER --pty -c "${*: 2}"
elif [ "$1" = "enter" ]; then
    distbox run bash
elif [ "$1" = "backup" ]; then
    read -r -p "Do you want to (override) backup your distbox? [y/N] " response
    if ! [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        exit
    fi

    echo y | distbox stop 1> /dev/null
    podman unshare rm -rf $DISTBOX_FILES@backup
    podman unshare cp -R -a $DISTBOX_FILES $DISTBOX_FILES@backup
elif [ "$1" = "stop" ]; then
    read -r -p "Do you want to stop your distbox? [y/N] " response
    if ! [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        exit
    fi

    HOME=$DISTBOX_PODMAN podman stop my-distbox
elif [ "$1" = "uninstall" ]; then
    read -r -p "Do you want to uninstall your distbox? [y/N] " response
    if ! [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        exit
    fi

    echo y | distbox stop 1> /dev/null 2> /dev/null

    podman unshare chown root: -R $DISTBOX_PODMAN/.local/share/containers/storage 2> /dev/null
    podman unshare rm -rf $DISTBOX_PODMAN 2> /dev/null
    rm -rf $DISTBOX_FILES
else
    echo $'Valid commands: \n'
    echo 'distbox install'
    echo 'distbox run COMMAND'
    echo 'distbox enter'
    echo 'distbox backup'
    echo 'distbox stop'
    echo 'distbox uninstall'
fi
